import { Component, OnInit } from '@angular/core';
import * as AOS from 'aos';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss']
})
export class AboutComponent implements OnInit {
  statList: Array<any> = [
    {id: 0, name: "Movies", number: 664667},
    {id: 1, name: "TV Shows", number: 112859},
    {id: 2, name: "TV Seasons", number: 172745},
    {id: 3, name: "TV Episodes", number: 2655368},
    {id: 4, name: "People", number: 2120540},
    {id: 5, name: "Images", number: 2745936},
    {id: 6, name: "Edits Last Week", number: 284210},
    {id: 7, name: "Stats", number: 1},
  ];
  stories = [
    {year: "2007", title: "Hulu is Founded", direction: "row", image: "../../../../assets/images/hulu2007.png", imageHeight: "300px", imageWidth: "350px", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-left", animatePara: "fade-right"},
    {year: "2008", title: "", direction: "row-reverse", image: "../../../../assets/images/hulu2008.jpg", imageHeight: "300px", imageWidth: "350px", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2009", title: "Hulu first Super Bowl ad airs", direction: "column", image: "../../../../assets/images/hulu2009.jpg", imageHeight: "500px", imageWidth: "100%", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2010", title: "Hulu launchs subcriptions service", direction: "column-reverse", image: "../../../../assets/images/hulu2010.jpg", imageHeight: "500px", imageWidth: "100%", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "flip-right", animatePara: "zoom-in-up"},
    {year: "2011", title: "A day in a life", direction: "column", image: "../../../../assets/images/hulu2011.jpg", imageHeight: "500px", imageWidth: "100%", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "zoom-in-right", animatePara: "flip-left"},
    {year: "2012", title: "Hits 1 million subscribers", direction: "row-reverse", image: "../../../../assets/images/hulu2012.jpg", imageHeight: "300px", imageWidth: "350px", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "zoom-out-up", animatePara: "fade-down-left"},
    {year: "2013", title: "Showtime becomes the first premium", direction: "column", image: "../../../../assets/images/hulu2013.png", imageHeight: "500px", imageWidth: "100%", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2014", title: "Hulu gives subscribers more choice", direction: "row-reverse", image: "../../../../assets/images/hulu2014.jpg", imageHeight: "300px", imageWidth: "350px", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2015", title: "Hits 10 million subscribers", direction: "row", image: "../../../../assets/images/hulu2015.jpg", imageHeight: "300px", imageWidth: "350px", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2016", title: "Hulu goes live with Live TV", direction: "column", image: "../../../../assets/images/hulu2016.jpg", imageHeight: "500px", imageWidth: "100%", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "zoom-out", animatePara: "flip-right"},
    {year: "2017", title: "Becomes the first streaming service", direction: "row-reverse", image: "../../../../assets/images/hulu2017.jpg", imageHeight: "300px", imageWidth: "350px", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2018", title: "Hulu celebrates 10 years", direction: "column-reverse", image: "../../../../assets/images/hulu2018.jpg", imageHeight: "500px", imageWidth: "100%", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2019", title: "Walt Disney Company assumes full operational control of Hulu", direction: "column", image: "../../../../assets/images/hulu2019.jpg", imageHeight: "500px", imageWidth: "100%", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "zoom-out-down", animatePara: "flip-left"},
    {year: "2020", title: "The TMDb product, service, attitude and support are truly top notch", direction: "row", image: "../../../../assets/images/hulu2020.png", imageHeight: "300px", imageWidth: "350px", paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "zoom-out-up", animatePara: "fade-up-right"},
];

  constructor() { 
    AOS.init();
  };

  ngOnInit(): void {};



}
